[supervisord]
nodaemon=true
user=root

[program:pulseaudio]
command=/usr/bin/pulseaudio --system --disallow-exit
autostart=true
autorestart=true
priority=10
startretries=3
startsecs=2
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:shairport-sync]
command=/usr/bin/shairport-sync -a "%(ENV_SOUND_DEVICE_NAME)s" --output alsa -- -d pulse
autostart=true
autorestart=true
priority=20
startretries=3
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
